# Generated by Django 2.1.5 on 2019-01-19 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockInModel',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ClockInModel', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('time', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='authmodel',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='AuthModel', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
