# Generated by Django 2.1.5 on 2019-01-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clockinmodel',
            name='id',
        ),
        migrations.DeleteModel(
            name='AuthModel',
        ),
        migrations.DeleteModel(
            name='ClockInModel',
        ),
    ]
