# Generated by Django 2.1.5 on 2019-01-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190122_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sheet_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
